### ISSUE TITLE
Format for json file(s)?

### ISSUE THREAD

**Issue by ethanKlein** [angular-translate/bower-angular-translate-loader-url#3]
Hi. Thanks for the contributions you've made to the angular-translate ecosystem! We've enjoyed using it thus far. 

I'm currently struggling to wire-up angular-translate-loader-url. I'm unsure of what the expected structure of the json file(s) should be, or if there should be separate json files for each language?

Currently angular-translate is working great by itself. When I replace the separate $translateProvider.tranlations functions with:
$translateProvider.useUrlLoader('json/i18n.json');
$translateProvider.preferredLanguage('sp'); 

The system successfully loads my json file but the translation filters no longer work. I think there is something wrong with how I'm structuring the json. I'm unsure of what angular-translate-loader-url expects?
Here's my i18n.json
{ 
  "en": {
    "BACK": "Back",
    "SKIP": "Skip"
  },

  "sp": {
    "BACK": "Anterior",
    "SKIP": "Siguiente"    
  },

  "jp": {
    "BACK": "前",
    "SKIP": "次"    
  }
}

Thanks so much!!!
It would be great to see a plunker or example of all the parts necessary to make angular-translate-loader-url work!

**Comment by PascalPrecht** [comment]
Please open the issue on the main repo
http://github.com/angular-translate/angular-translate.

Thanks!

On Fri, Jan 30, 2015 at 8:52 PM, ethanKlein <notifications@github.com>
wrote:

> Hi. Thanks for the contributions you've made to the angular-translate
> ecosystem! We've enjoyed using it thus far.
>
> I'm currently struggling to wire-up angular-translate-loader-url. I'm
> unsure of what the expected structure of the json file(s) should be, or if
> there should be separate json files for each language?
>
> Currently angular-translate is working great by itself. When I replace the
> separate $translateProvider.tranlations functions with:
> $translateProvider.useUrlLoader('json/i18n.json');
> $translateProvider.preferredLanguage('sp');
>
> The system successfully loads my json file but the translation filters no
> longer work. I think there is something wrong with how I'm structuring the
> json. I'm unsure of what angular-translate-loader-url expects?
> Here's my i18n.json
> {
> "en": {
> "BACK": "Back",
> "SKIP": "Skip"
> },
>
> "sp": {
> "BACK": "Anterior",
> "SKIP": "Siguiente"
>
> },
>
> "jp": {
> "BACK": "前",
> "SKIP": "次"
>
> }
> }
>
> Thanks so much!!!
> It would be great to see a plunker or example of all the parts necessary
> to make angular-translate-loader-url work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-translate/bower-angular-translate-loader-url/issues/3>
> .
>



-- 
/pp
